[platformio]
default_envs = lilygo-t-display-s3

[common]
framework = arduino
platform = espressif32@6.6.0
monitor_speed = 115200
lib_deps =
    https://github.com/tzapu/WiFiManager.git
build_flags =
    -DCORE_DEBUG_LEVEL=3

[env:lilygo-t-display-s3]
extends = common
board = lilygo-t-display-s3
build_flags =
    ${common.build_flags}
    -DBOARD_TDISPLAY_S3
    -DNERDMINERV2=1

[env:lilygo-t-qt-pro]
extends = common
board = esp32-s3-t-qt-pro
build_flags =
    ${common.build_flags}
    -DBOARD_TQT_PRO
    -DBOARD_HAS_PSRAM
    -DNERDMINER_T_QT=1