[platformio]
default_envs = lilygo-t-display-s3

[common_base]
framework = arduino
platform = espressif32@6.6.0
monitor_speed = 115200
lib_deps =
    https://github.com/tzapu/WiFiManager.git#4131fe6

[common_release]
extends = common_base
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=1

[common_debug]
extends = common_base
build_type = debug
build_flags =
    -DCORE_DEBUG_LEVEL=4

[env:lilygo-t-display-s3-release]
extends = common_release
board = lilygo-t-display-s3
build_flags =
    ${common_release.build_flags}
    -DBOARD_TDISPLAY_S3
    -DNERDMINERV2=1

[env:lilygo-t-display-s3-debug]
extends = common_debug
board = lilygo-t-display-s3
build_flags =
    ${common_debug.build_flags}
    -DBOARD_TDISPLAY_S3
    -DNERDMINERV2=1

[env:lilygo-t-qt-pro-release]
extends = common_release
board = esp32-s3-t-qt-pro
build_flags =
    ${common_release.build_flags}
    -DBOARD_TQT_PRO
    -DNERDMINER_T_QT=1

[env:lilygo-t-qt-pro-debug]
extends = common_debug
board = esp32-s3-t-qt-pro
build_flags =
    ${common_debug.build_flags}
    -DBOARD_TQT_PRO
    -DNERDMINER_T_QT=1

[env:lilygo-t-display-s3]
extends = env:lilygo-t-display-s3-release

[env:lilygo-t-qt-pro]
extends = env:lilygo-t-qt-pro-release

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    -<*>
    +<modules/buttons/buttons_logic.cpp>
    +<modules/storage/storage_io.cpp>
    +<modules/wifi/wifi_config.cpp>
