[platformio]
default_envs = lilygo-t-display-s3

[common_base]
framework = arduino
platform = espressif32@6.6.0
monitor_speed = 115200
lib_deps =
    https://github.com/tzapu/WiFiManager.git#4131fe6

[env:lilygo-t-display-s3]
extends = common_base
board = lilygo-t-display-s3
build_type = release
lib_deps =
    ${common_base.lib_deps}
    h2zero/NimBLE-Arduino@^1.4.2
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_TDISPLAY_S3
    -DNERDMINERV2=1
    -DFEATURE_OTA=1
    -DFEATURE_BLE=1

[env:lilygo-t-qt-pro]
extends = common_base
board = esp32-s3-t-qt-pro
build_type = release
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DBOARD_TQT_PRO
    -DNERDMINER_T_QT=1
    -DFEATURE_OTA=0
    -DFEATURE_BLE=0

[env:native]
platform = native
test_framework = unity
test_build_src = yes
build_src_filter =
    -<*>
    +<modules/buttons/buttons_logic.cpp>
    +<modules/storage/storage_io.cpp>
    +<modules/wifi/wifi_config.cpp>
